### ISSUE TITLE
add texas BTM robberies

### ISSUE THREAD

**Issue by jlopp** [jlopp/physical-bitcoin-attacks#31]
https://www.wfaa.com/article/news/crime/thieves-caught-on-camera-robbing-bitcoin-machine-at-irving-gas-station/287-543254631

**Comment by kenorb** [comment]
The link is dead.

**Comment by jlopp** [comment]
https://www.dallasnews.com/news/crime/2018/04/20/robbers-douse-clerks-with-pepper-spray-steal-from-bitcoin-atms-in-irving-and-mesquite/
