### ISSUE TITLE
Do the Attacks have to be Successful?  (with Netherlands Example)

### ISSUE THREAD

**Issue by HysMagus** [jlopp/physical-bitcoin-attacks#35]
For example
https://nltimes.nl/2020/02/02/violent-robbery-bitcoin-trader-included-water-boarding-power-drill 
in the Netherlands, they tortured this guy for Bitcoin and other digital assets but they didn't get anything. 
Feb 10th, 2018

**Comment by jlopp** [comment]
No, the only real requirement is that violence / a threat of physical violence was used. That incident is already in the repository.
