### ISSUE TITLE
Vernon Grocery Store BTM Robbery

### ISSUE THREAD

**Issue by HysMagus** [jlopp/physical-bitcoin-attacks#36]
https://www.castanet.net/news/Vernon/270823/Vernon-grocery-store-thieves-break-into-bitcoin-ATM
Vernon Grocery Store
November 19, 2019*
Edit: fix typo in date

**Comment by verretor** [comment]
2020?

**Comment by HysMagus** [comment]
Thanks, fixed the typo in the date
