### ISSUE TITLE
Add robbery in Taiwan

### ISSUE THREAD

**Issue by githorray** [jlopp/physical-bitcoin-attacks#4]
http://www.arabnews.com/node/1251816/world
https://www.youtube.com/watch?v=0-WMdjLLlvo
http://news.ltn.com.tw/news/society/breakingnews/2345535
https://tw.appledaily.com/new/realtime/20180221/1301291/

Date: 2018-02
Victim: Tai
Location: Taichung, Taiwan
Description: Bitcoin seller assaulted and robbed of 18 BTC.

**Comment by jlopp** [comment]
Thanks; added in b1ae604
