### ISSUE TITLE
kidnap & ransom 

### ISSUE THREAD

**Issue by JayOceans** [jlopp/physical-bitcoin-attacks#5]
date
Sept 20, 2017
victim
Wong Yuk-kwan
location
Taipei, Taiwan
description
billionaire kidnapped for 38 days & ransomed for ~$9M

// thanks for all your work about this serious issue Jameson !!!

**Comment by JayOceans** [comment]
http://www.dailymail.co.uk/news/peoplesdaily/article-3295463/Hong-Kong-oil-tycoon-rescued-abducted-held-6-million-ransom-38-days.html

**Comment by jlopp** [comment]
Hmmmmm this is interesting because they demanded ransom in BTC, but I don't think it quite fits the profile for which I'm collecting, which is physical attacks that target owners of crypto assets. This guy was an oil tycoon who didn't have any ties to crypto.
