### ISSUE TITLE
January 16 2024, Romanian businessman gets kidnapped, gets his finger cut, $200K USD in crypto stolen

### ISSUE THREAD

**Issue by crazflood** [jlopp/physical-bitcoin-attacks#77]
Source : https://observatornews.ro/eveniment/celebru-om-de-afaceri-din-cluj-rapit-si-torturat-pentru-codul-de-la-criptomonede-talharii-iau-taiat-un-deget-558888.html    (In Romanian)

Summary:
In the night from 15 to 16 january, a 42 year old restaurant owner in Cluj, Romania was lured by an acquaintance to an abandoned construction hall, the initial reason was "to ask him some advices in crypto", after 15 minutes, two other masked men appeared, tied him, and for the next few hours they tortured him, threatened to kill him, doused gasoline on him and cut part of his finger, all to get access to his crypto. The man finally gave in and the robbers managed to transfer the crypto valued at around $200K USD, they also took his smartphone, two laptops, and his wedding before disappearing. 
There is currently an ongoing investigation

| January 16, 2024 | 42 y/o man | Cluj, Romania | [Restaurant owner kidnapped, tortured, doused in gasoline, gets part of his finger cut off, about $200K USD in crypto stolen.] 

I'm a noob and don't really know how github and pull requests work, i just wanted to share this

**Comment by jlopp** [comment]
Thanks for reporting!
