### ISSUE TITLE
Scope of repository 

### ISSUE THREAD

**Issue by 0xmatt11** [jlopp/physical-bitcoin-attacks#88]
Are Physical Attacks Enabled by Psychological Intermediaries?

Could psychological manipulation, like social engineering or coercion, serve as a precursor to physical attacks in your framework? Curious if this connection fits or if it's already implicit in your model.  If strictly physical, recorded attacks by a news outlet, understandable but could you specify a strict description of a scope ?

**Comment by jlopp** [comment]
I don't consider social engineering or other forms of remote / non-physical manipulation to be in scope for the purposes of this repository. Such attacks are extremely common and not particularly interesting for tracking purposes.

Scope for this repository basically requires that an attacker needs to have taken physical action to threaten / rob / assault / steal from a crypto asset owner. The owner could be an individual or an organization / business. The important attribute is that the attacker needs to be putting themselves at physical risk of being harmed while perpetrating the attack.

**Comment by 0xmatt11** [comment]
Thank you for the clarification
