### ISSUE TITLE
Technically not an attack but something worth mentioning (Consensys and DEVCON3)

### ISSUE THREAD

**Issue by stefek99** [jlopp/physical-bitcoin-attacks#9]
https://www.reddit.com/r/ethereum/comments/79pewg/corrupted_cops_locals_crypto_gangs_at_ethereum/dp4es6z/?context=3

> We hired a security company composed of Navy Seals and after weeks of research and discussion it was decided that this was too high profile an event in a slightly dangerous locale. The Navy Seals were relieved as protecting a large crew like that would have been difficult in that context (corrupt police, etc.). I would be happy to take a large group to Cancun/Tulum (I spent a chunk of time in Tulum -- it is wonderful) on another date, but during an event that is globally advertised to have lots of millionaires present who could easily give up instant access to large instantly disposable wealth, gave us pause. When the security firm let us know that the cartels had people on payroll at each hotel and knew exactly what was going on in the region, our company-wide discussion yielded agreement that we should not make it a corporate sponsored event.

**Comment by jlopp** [comment]
Yeah, physical threats are a rising problem in general. Going to keep this repository focused on actual attacks to prevent scope creep from making it too generic

**Comment by stefek99** [comment]
Policia municipal
Policia federal
Policia turistica
Corruption = protection

Each guys looking at each other, so that noone steals the most.

You've been to Cancun for Satoshi Roundtable, you know how it is :)

Much appreciating all the amazing work you do ! ! !
